export const seed = async (knex) => {
  await knex("scores").del();
  await knex("users").del();
  await knex("animals").del();
  await knex("categories").del();

  const categoryIds = await knex("categories")
    .insert([
      { name: "underwater" },
      { name: "wild" },
      { name: "birds" },
      { name: "insects" },
      { name: "farm" },
    ])
    .returning("id");

  await knex("animals").insert([
    { name: "dolphin", category_id: categoryIds[0] },
    { name: "lion", category_id: categoryIds[1] },
    { name: "eagle", category_id: categoryIds[2] },
    { name: "bee", category_id: categoryIds[3] },
    { name: "cow", category_id: categoryIds[4] },
    { name: "shark", category_id: categoryIds[0] },
    { name: "walrus", category_id: categoryIds[0] },
    { name: "stingray", category_id: categoryIds[0] },
    { name: "sea turtle", category_id: categoryIds[0] },
    { name: "narwhal", category_id: categoryIds[0] },
    { name: "seal", category_id: categoryIds[0] },
    { name: "whale", category_id: categoryIds[0] },
    { name: "starfish", category_id: categoryIds[0] },
    { name: "orca", category_id: categoryIds[0] },
    { name: "crab", category_id: categoryIds[0] },
    { name: "lobster", category_id: categoryIds[0] },
    { name: "sea lion", category_id: categoryIds[0] },
    { name: "jellyfish", category_id: categoryIds[0] },
    { name: "seahorse", category_id: categoryIds[0] },
    { name: "octopus", category_id: categoryIds[0] },
    { name: "clownfish", category_id: categoryIds[0] },
    { name: "sea otter", category_id: categoryIds[0] },
    { name: "eel", category_id: categoryIds[0] },
    { name: "crocodile", category_id: categoryIds[1] },
    { name: "monkey", category_id: categoryIds[1] },
    { name: "tiger", category_id: categoryIds[1] },
    { name: "kangaroo", category_id: categoryIds[1] },
    { name: "cheetah", category_id: categoryIds[1] },
    { name: "wolf", category_id: categoryIds[1] },
    { name: "leapard", category_id: categoryIds[1] },
    { name: "meerkat", category_id: categoryIds[1] },
    { name: "deer", category_id: categoryIds[1] },
    { name: "koala", category_id: categoryIds[1] },
    { name: "squirrel", category_id: categoryIds[1] },
    { name: "hippopotamus", category_id: categoryIds[1] },
    { name: "armadillo", category_id: categoryIds[1] },
    { name: "fox", category_id: categoryIds[1] },
    { name: "skunk", category_id: categoryIds[1] },
    { name: "panther", category_id: categoryIds[1] },
    { name: "tortoise", category_id: categoryIds[1] },
    { name: "zebra", category_id: categoryIds[1] },
    { name: "giraffe", category_id: categoryIds[1] },
    { name: "rhinoceros", category_id: categoryIds[1] },
    { name: "coyote", category_id: categoryIds[1] },
    { name: "hedgehog", category_id: categoryIds[1] },
    { name: "polar bear", category_id: categoryIds[1] },
    { name: "snake", category_id: categoryIds[1] },
    { name: "elephant", category_id: categoryIds[1] },
    { name: "bear", category_id: categoryIds[1] },
    { name: "panda", category_id: categoryIds[1] },
    { name: "gorilla", category_id: categoryIds[1] },
    { name: "hummingbird", category_id: categoryIds[2] },
    { name: "macaw", category_id: categoryIds[2] },
    { name: "kingfisher", category_id: categoryIds[2] },
    { name: "ostrich", category_id: categoryIds[2] },
    { name: "pigeon", category_id: categoryIds[2] },
    { name: "penguin", category_id: categoryIds[2] },
    { name: "rooster", category_id: categoryIds[2] },
    { name: "seagull", category_id: categoryIds[2] },
    { name: "parrot", category_id: categoryIds[2] },
    { name: "vulture", category_id: categoryIds[2] },
    { name: "goose", category_id: categoryIds[2] },
    { name: "peacock", category_id: categoryIds[2] },
    { name: "dove", category_id: categoryIds[2] },
    { name: "woodpecker", category_id: categoryIds[2] },
    { name: "swan", category_id: categoryIds[2] },
    { name: "hen", category_id: categoryIds[2] },
    { name: "turkey", category_id: categoryIds[2] },
    { name: "toucan", category_id: categoryIds[2] },
    { name: "flamingo", category_id: categoryIds[2] },
    { name: "falcon", category_id: categoryIds[2] },
    { name: "owl", category_id: categoryIds[2] },
    { name: "duck", category_id: categoryIds[2] },
    { name: "sparrow", category_id: categoryIds[2] },
    { name: "owl", category_id: categoryIds[2] },
    { name: "cockroach", category_id: categoryIds[3] },
    { name: "ant", category_id: categoryIds[3] },
    { name: "ladybug", category_id: categoryIds[3] },
    { name: "caterpillar", category_id: categoryIds[3] },
    { name: "housefly", category_id: categoryIds[3] },
    { name: "firefly", category_id: categoryIds[3] },
    { name: "grasshopper", category_id: categoryIds[3] },
    { name: "beetle", category_id: categoryIds[3] },
    { name: "praying mantis", category_id: categoryIds[3] },
    { name: "wasp", category_id: categoryIds[3] },
    { name: "dragonfly", category_id: categoryIds[3] },
    { name: "cricket", category_id: categoryIds[3] },
    { name: "mosquito", category_id: categoryIds[3] },
    { name: "butterfly", category_id: categoryIds[3] },
    { name: "donkey", category_id: categoryIds[4] },
    { name: "goat", category_id: categoryIds[4] },
    { name: "buffalo", category_id: categoryIds[4] },
    { name: "cat", category_id: categoryIds[4] },
    { name: "horse", category_id: categoryIds[4] },
    { name: "guinea pig", category_id: categoryIds[4] },
    { name: "pig", category_id: categoryIds[4] },
    { name: "rabbit", category_id: categoryIds[4] },
    { name: "llama", category_id: categoryIds[4] },
    { name: "sheep", category_id: categoryIds[4] },
    { name: "mouse", category_id: categoryIds[4] },
    { name: "dog", category_id: categoryIds[4] },
  ]);

  const userIds = await knex("users")
    .insert([{ name: "Alice" }, { name: "Bob" }])
    .returning("id");

  await knex("scores").insert([
    { user_id: userIds[0], score: 100 },
    { user_id: userIds[1], score: 80 },
  ]);
};
